### ISSUE TITLE
Add pending harvest indicator for connected wallet

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#242]
**When I** connect my wallet to the pickle site
**I want** to see my share of pending harvests that involve jars and farms I have deposited or staked money in
**So that** I can determine how much money is coming my way from that harvest.

**Comment by janklimo** [comment]
@mannyreimi88 @bcstryker can you share more details for this?

**Comment by bcstryker** [comment]
@janklimo 
When I connect my wallet to the pickle site
I want to see my share of pending harvests that involve jars and farms I have deposited or staked money in
So that I can determine how much money is coming my way from that harvest.

To accomplish this task, you can use the pf-core API to determine the current wallet's pToken balance for a given jar, the total number of pTokens that exist in a given jar, and the total pending harvest. With math, you should be able to determine the wallet's share of the harvest.
