### ISSUE TITLE
Farms are stuck in loading state indefinitely 

### ISSUE THREAD

**Issue by mikeyobrien** [pickle-finance/pickle-ui#95]
![image](https://user-images.githubusercontent.com/11792047/125644299-f2a36ee9-4ea2-4db4-9c45-d0c41cb87dc8.png)

Checking the console logs, 

```
[Error] Fetch API cannot load https://cloudflare-eth.com/ due to access control checks.
[Error] Failed to load resource: Origin https://app.pickle.finance is not allowed by Access-Control-Allow-Origin. (cloudflare-eth.com, line 0)
```

This is on Safari

**Comment by janklimo** [comment]
Thank you @mikeyobrien for reporting this. Given that the console error refers to missing CORS headers, this was a server error that returned a non-standard response. Lately those were due to The Graph not working properly which has been resolved. I'll close this but feel free to reopen if it becomes a problem again.
